baseurl: '/'
permalink: /:title/
title: 'hamish.com.au'

bootstrap:
  date_format: "%b %-d, %Y"

  header_pages:
  - services.md
  - software.md
  - about.md
  - contact.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  services:
    output: true

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md